# Generated by Django 3.1.7 on 2021-04-02 07:26

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
        name='Item',
        fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('description', models.CharField(max_length=100, verbose_name='Description')),
        ('is_completed', models.BooleanField(default=False, verbose_name='Is completed?')),],
        ),]
