# Generated by Django 3.2.9 on 2021-11-23 11:44

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
        name='KV',
        fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('key', models.CharField(max_length=120, unique=True)),
        ('value', models.TextField()),],
        ),]
