# portainer stack settings:
#     name: hypergen
#     repo:https://github.com/runekaagaard/django-hypergen
#     path: docker-compose/hypergen_examples/docker-compose.yml

version: '3.8'

services:
  web:
    entrypoint: /entrypoint.sh
    pull_policy: build # required to get portainer rebuilding the image on succesive deploys. ZZZ.
    build:
      context: /home/r/ws/django-hypergen
      dockerfile: docker-compose/hypergen_examples/Dockerfile
    working_dir: /code/examples
    volumes:
      - static_volume:/static
      - /home/r/ws/django-hypergen:/code/local-source
    depends_on:
      - redis
    environment:
      PROD: "true"
    ports:
      - "9876:8000"  # Expose Django on port 9876

  # serve static files.
  nginx:
    pull_policy: build # required to get portainer rebuilding the image on succesive deploys. ZZZ.
    build:
      context: /home/r/ws/django-hypergen
      dockerfile: docker-compose/hypergen_examples/DockerfileNginx
    volumes:
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - web

  redis:
    image: "redis:alpine"
    
volumes:
  static_volume:
