# portainer stack settings:
#     name: hypergen
#     repo:https://github.com/runekaagaard/django-hypergen
#     path: docker-compose/hypergen_examples/docker-compose.yml

version: '3.8'

services:
  web:
    entrypoint: /entrypoint.sh
    pull_policy: build # required to get portainer rebuilding the image on succesive deploys. ZZZ.
    build:
      context: ../../
      dockerfile: docker-compose/hypergen_examples/Dockerfile
    working_dir: /code/examples
    volumes:
      - static_volume:/static
    depends_on:
      - redis
    environment:
      PROD: true
    networks:
      - nginx-uptime-proxy_default
      - hypergen_default


  # serve static files.
  nginx:
    pull_policy: build # required to get portainer rebuilding the image on succesive deploys. ZZZ.
    build:
      context: ../../
      dockerfile: docker-compose/hypergen_examples/DockerfileNginx
    volumes:
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - web
    networks:
      - nginx-uptime-proxy_default
      - hypergen_default

  redis:
    image: "redis:alpine"
    
networks:
  # Nginx proxy manager network.
  nginx-uptime-proxy_default:
    external: true
  # Network for hypergen stack.
  hypergen_default:
    external: true
      
volumes:
  static_volume:
