# portainer settings:
#     https://github.com/runekaagaard/django-hypergen
#     

version: '3.8'

services:
  web:
    entrypoint: /entrypoint.sh
    build:
      context: ../../
      dockerfile: docker-compose/hypergen_examples/Dockerfile
    working_dir: /code/examples
    volumes:
      - static_volume:/static
    depends_on:
      - redis
    environment:
      PROD: true

  redis:
    image: "redis:alpine"

  # local testing. No websocket support.
  nginx:
    build:
      context: ../../
      dockerfile: docker-compose/hypergen_examples/DockerfileNginx
    ports:
      - "8888:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - web

volumes:
  static_volume:
