# portainer settings:
#     https://github.com/runekaagaard/django-hypergen
#     

version: '3.8'

services:
  web:
    entrypoint: /entrypoint.sh
    build:
      context: ../../
      dockerfile: docker-compose/hypergen_examples/Dockerfile
    working_dir: /code/examples
    volumes:
      - static_volume:/static
    depends_on:
      - redis
    environment:
      PROD: true
    networks:
      - nginx-uptime-proxy_default
      - hypergen_default

  redis:
    image: "redis:alpine"

  # serve static files.
  nginx:
    build:
      context: ../../
      dockerfile: docker-compose/hypergen_examples/DockerfileNginx
    ports:
      - "8888:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - web
    networks:
      - nginx-uptime-proxy_default
      - hypergen_default

networks:
  # Nginx proxy manager network.
  nginx-uptime-proxy_default:
    external: true
  # Network for hypergen stack.
  hypergen_default:
    external: true
      
volumes:
  static_volume:
