name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: ${{ contains(github.event.commits[0].message, '[ci]') }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      matrix:
        include:
          - python-version: 3.4
            django-version: Django==1.11.29
          - python-version: 3.4
            django-version: Django==2.0.13
          - python-version: 3.4
            django-version: Django==2.1.15
          - python-version: 3.5
            django-version: Django==1.11.29
          - python-version: 3.5
            django-version: Django==2.0.13
          - python-version: 3.5
            django-version: Django==1.11.29
          - python-version: 3.6
            django-version: Django==2.2.28
          - python-version: 3.6
            django-version: Django==3.0.14
          - python-version: 3.6
            django-version: Django==3.1.14
          - python-version: 3.6
            django-version: Django==2.0.13
          - python-version: 3.7
            django-version: Django==1.11.29
          - python-version: 3.7
            django-version: Django==2.0.13
          - python-version: 3.7
            django-version: Django==2.1.15
          - python-version: 3.7
            django-version: Django==2.2.28
          - python-version: 3.7
            django-version: Django==3.0.14
          - python-version: 3.7
            django-version: Django==3.1.14
          - python-version: 3.7
            django-version: Django==3.2.13
          - python-version: 3.8
            django-version: Django==1.11.29
          - python-version: 3.8
            django-version: Django==2.0.13
          - python-version: 3.8
            django-version: Django==2.1.15
          - python-version: 3.8
            django-version: Django==2.2.28
          - python-version: 3.8
            django-version: Django==3.0.14
          - python-version: 3.8
            django-version: Django==3.1.14
          - python-version: 3.8
            django-version: Django==3.2.13
          - python-version: 3.8
            django-version: Django==4.0.4
          - python-version: 3.9
            django-version: Django==1.11.29
          - python-version: 3.9
            django-version: Django==2.0.13
          - python-version: 3.9
            django-version: Django==2.1.15
          - python-version: 3.9
            django-version: Django==2.2.28
          - python-version: 3.9
            django-version: Django==3.0.14
          - python-version: 3.9
            django-version: Django==3.1.14
          - python-version: 3.9
            django-version: Django==3.2.13
          - python-version: 3.9
            django-version: Django==4.0.4
          - python-version: "3.10"
            django-version: Django==3.2.13
          - python-version: "3.10"
            django-version: Django==4.0.4
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ${{ matrix.django-version }}
    - name: Run Tests
      run: |
        pytest --tb=native -vvvv src/hypergen/test_all.py
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Start Runserver
      run: |
        cd examples
        CSRF_DISABLE=1 python manage.py runserver 127.0.0.1:8002 &
    - name: Install testcafe
      run: npm install -g testcafe
    - name: Run testcafe tests
      run: make testcafe-run-headless
